#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# Connect4-Battle Production Deployment Script
# =============================================================================
# Generates nginx config, systemd units, and optionally sets up SSL.
# Usage: ./setup_production.sh [--ssl] [--domain <domain>]
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_NAME="connect4-battle"

# Load environment
if [ -f "$SCRIPT_DIR/.env.production" ]; then
    set -a; source "$SCRIPT_DIR/.env.production"; set +a
    echo "[OK] Loaded .env.production"
elif [ -f "$SCRIPT_DIR/.env" ]; then
    set -a; source "$SCRIPT_DIR/.env"; set +a
    echo "[OK] Loaded .env"
else
    echo "[WARN] No .env file found, using defaults"
fi

# Defaults
SERVICE_PORT_A="${SERVICE_PORT_A:-8081}"
SERVICE_PORT_B="${SERVICE_PORT_B:-8082}"
LOBBY_SERVICE_PORT="${LOBBY_SERVICE_PORT:-8083}"
FRONTEND_PORT_A="${FRONTEND_PORT_A:-5173}"
FRONTEND_PORT_B="${FRONTEND_PORT_B:-5174}"

# Parse arguments
SETUP_SSL=false
DOMAIN=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --ssl) SETUP_SSL=true; shift ;;
        --domain) DOMAIN="$2"; shift 2 ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

# =============================================================================
# Validation
# =============================================================================
echo ""
echo "=== Validating environment ==="

REQUIRED_VARS=(SERVICE_PORT_A SERVICE_PORT_B LOBBY_SERVICE_PORT FRONTEND_PORT_A FRONTEND_PORT_B)
MISSING=0
for var in "${REQUIRED_VARS[@]}"; do
    if [ -z "${!var:-}" ]; then
        echo "[ERROR] Missing required variable: $var"
        MISSING=1
    fi
done
if [ "$MISSING" -eq 1 ]; then
    echo "Copy .env.example to .env and fill in required values."
    exit 1
fi
echo "[OK] All required variables set"

# =============================================================================
# Generate nginx configuration
# =============================================================================
echo ""
echo "=== Generating nginx configuration ==="

NGINX_CONF="/etc/nginx/sites-available/$APP_NAME"
SERVER_NAME="${DOMAIN:-_}"

cat > "/tmp/$APP_NAME.nginx" <<NGINX_EOF
# Connect4-Battle nginx reverse proxy
# Generated by setup_production.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

upstream connect4_service_a {
    server 127.0.0.1:${SERVICE_PORT_A};
}

upstream connect4_service_b {
    server 127.0.0.1:${SERVICE_PORT_B};
}

upstream connect4_lobby {
    server 127.0.0.1:${LOBBY_SERVICE_PORT};
}

upstream connect4_frontend_a {
    server 127.0.0.1:${FRONTEND_PORT_A};
}

upstream connect4_frontend_b {
    server 127.0.0.1:${FRONTEND_PORT_B};
}

server {
    listen 80;
    server_name ${SERVER_NAME};

    # Security headers
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    add_header Referrer-Policy strict-origin-when-cross-origin;

    # CORS headers
    add_header Access-Control-Allow-Origin *;
    add_header Access-Control-Allow-Methods "GET, POST, OPTIONS";
    add_header Access-Control-Allow-Headers "Content-Type, Authorization";

    # Player A frontend
    location / {
        proxy_pass http://connect4_frontend_a;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    # Player B frontend
    location /player-b/ {
        proxy_pass http://connect4_frontend_b/;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
    }

    # GraphQL service A
    location /api/service-a/ {
        proxy_pass http://connect4_service_a/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_read_timeout 86400;
    }

    # GraphQL service B
    location /api/service-b/ {
        proxy_pass http://connect4_service_b/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_read_timeout 86400;
    }

    # Lobby service
    location /api/lobby/ {
        proxy_pass http://connect4_lobby/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_read_timeout 86400;
    }

    # Health check endpoint
    location /health {
        access_log off;
        return 200 '{"status":"ok","service":"connect4-battle"}';
        add_header Content-Type application/json;
    }
}
NGINX_EOF

echo "[OK] nginx config written to /tmp/$APP_NAME.nginx"

if [ -w "/etc/nginx/sites-available" ] 2>/dev/null; then
    cp "/tmp/$APP_NAME.nginx" "$NGINX_CONF"
    ln -sf "$NGINX_CONF" "/etc/nginx/sites-enabled/$APP_NAME"
    nginx -t && systemctl reload nginx
    echo "[OK] nginx config installed and reloaded"
else
    echo "[INFO] Run with sudo to install nginx config:"
    echo "  sudo cp /tmp/$APP_NAME.nginx $NGINX_CONF"
    echo "  sudo ln -sf $NGINX_CONF /etc/nginx/sites-enabled/$APP_NAME"
    echo "  sudo nginx -t && sudo systemctl reload nginx"
fi

# =============================================================================
# Generate systemd service units
# =============================================================================
echo ""
echo "=== Generating systemd service units ==="

for ROLE in service-a service-b lobby; do
    case "$ROLE" in
        service-a) PORT="$SERVICE_PORT_A" DESC="Player A GraphQL Service" ;;
        service-b) PORT="$SERVICE_PORT_B" DESC="Player B GraphQL Service" ;;
        lobby)     PORT="$LOBBY_SERVICE_PORT" DESC="Lobby/Master Chain Service" ;;
    esac

    cat > "/tmp/$APP_NAME-$ROLE.service" <<SYSTEMD_EOF
[Unit]
Description=Connect4-Battle $DESC
After=network.target
Wants=network-online.target

[Service]
Type=simple
User=linera
Group=linera
WorkingDirectory=$SCRIPT_DIR
Environment=RUST_LOG=${RUST_LOG:-info}
ExecStart=/usr/local/bin/linera service --port $PORT
Restart=on-failure
RestartSec=5
StartLimitIntervalSec=60
StartLimitBurst=5

# Resource limits
LimitNOFILE=65535
MemoryMax=1G
CPUQuota=100%

# Security hardening
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
PrivateTmp=true

[Install]
WantedBy=multi-user.target
SYSTEMD_EOF

    echo "[OK] Systemd unit: /tmp/$APP_NAME-$ROLE.service"
done

if [ -w "/etc/systemd/system" ] 2>/dev/null; then
    for ROLE in service-a service-b lobby; do
        cp "/tmp/$APP_NAME-$ROLE.service" "/etc/systemd/system/$APP_NAME-$ROLE.service"
    done
    systemctl daemon-reload
    echo "[OK] Systemd units installed"
else
    echo "[INFO] Run with sudo to install systemd units:"
    echo "  sudo cp /tmp/$APP_NAME-*.service /etc/systemd/system/"
    echo "  sudo systemctl daemon-reload"
    echo "  sudo systemctl enable $APP_NAME-service-a $APP_NAME-service-b $APP_NAME-lobby"
fi

# =============================================================================
# SSL setup (optional)
# =============================================================================
if [ "$SETUP_SSL" = true ]; then
    echo ""
    echo "=== Setting up SSL with Certbot ==="

    if [ -z "$DOMAIN" ]; then
        echo "[ERROR] --domain is required for SSL setup"
        exit 1
    fi

    if ! command -v certbot &>/dev/null; then
        echo "[INFO] Installing certbot..."
        apt-get update && apt-get install -y certbot python3-certbot-nginx
    fi

    certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos --redirect \
        --email "admin@$DOMAIN" || {
        echo "[ERROR] Certbot failed. Make sure DNS is configured."
        exit 1
    }
    echo "[OK] SSL configured for $DOMAIN"
fi

# =============================================================================
# Health check verification
# =============================================================================
echo ""
echo "=== Running health checks ==="

check_port() {
    local name="$1" port="$2"
    if curl -sf "http://localhost:$port" >/dev/null 2>&1; then
        echo "[OK] $name (port $port) is responding"
    else
        echo "[WARN] $name (port $port) is not responding"
    fi
}

check_port "Frontend A"  "$FRONTEND_PORT_A"
check_port "Frontend B"  "$FRONTEND_PORT_B"
check_port "Service A"   "$SERVICE_PORT_A"
check_port "Service B"   "$SERVICE_PORT_B"
check_port "Lobby"       "$LOBBY_SERVICE_PORT"

echo ""
echo "=== Production setup complete ==="
echo ""
echo "Generated files:"
echo "  nginx:   /tmp/$APP_NAME.nginx"
echo "  systemd: /tmp/$APP_NAME-service-a.service"
echo "  systemd: /tmp/$APP_NAME-service-b.service"
echo "  systemd: /tmp/$APP_NAME-lobby.service"
if [ -n "$DOMAIN" ]; then
    echo ""
    echo "Access at: https://$DOMAIN"
else
    echo ""
    echo "Access at: http://localhost:$FRONTEND_PORT_A (Player A)"
    echo "           http://localhost:$FRONTEND_PORT_B (Player B)"
fi
