[package]
name = "connect4"
version = "0.1.0"
edition = "2021"

[dependencies]
abi.workspace = true
bankroll.workspace = true
async-graphql.workspace = true
async-graphql-derive.workspace = true
log.workspace = true
linera-sdk.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio = { workspace = true, features = ["rt", "sync"] }
linera-sdk = { workspace = true, features = ["test", "wasmer"] }

[dev-dependencies]
linera-sdk = { workspace = true, features = ["test"] }

[[bin]]
name = "connect4_contract"
path = "src/contract.rs"

[[bin]]
name = "connect4_service"
path = "src/service.rs"
